//Try catch
const number1 = 20;
const number2 = 30;

console.log(number1);
try {
    console.log(number3);
} catch (error) {
    console.log(error);
}
console.log(number2);